# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4fb6d1507fb80c2be9808f67abf811fec5be03398b84d76647c5ae5e3f946a039fca82da7fa3447b7d4d52aa0af0d3c53f03739b1f94e6cfcc7b64f6deba249

test:
  secret_key_base: fe3f17ec51fb2baeb7a5edd5679a583ac255b523c44f4647efafa958a637fa81a43e4979f8764b10a657da88d64b928a40ff569eb754b3e2af35dba4a686e44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
